// Generated by jextract

package org.example.panama;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {
    }

    static final FunctionDescriptor demo_sum$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
            Constants$root.C_INT$LAYOUT,
            Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle demo_sum$MH = RuntimeHelper.downcallHandle(
            "demo_sum",
            constants$0.demo_sum$FUNC
    );
    static final FunctionDescriptor demo_generate_hello$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
            Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle demo_generate_hello$MH = RuntimeHelper.downcallHandle(
            "demo_generate_hello",
            constants$0.demo_generate_hello$FUNC
    );
    static final FunctionDescriptor get_by_id$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
            Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle get_by_id$MH = RuntimeHelper.downcallHandle(
            "get_by_id",
            constants$0.get_by_id$FUNC
    );
    static final FunctionDescriptor get_by_name_like$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
            Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle get_by_name_like$MH = RuntimeHelper.downcallHandle(
            "get_by_name_like",
            constants$0.get_by_name_like$FUNC
    );
}


